[package]
name = "anki-widget"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
anki = { git = "https://github.com/ankitects/anki.git" }
clap = { version = "4.5.23", features = ["derive"] }
color-eyre = { version = "0.6.3", default-features = false }
