name: Build and release

on:
  push:
    # complemented with branch protection on main this will 
    # run on any pull request merge
    branches: main 

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  compile:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ matrix.target }}
        toolchain: stable

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          compilers/
        key: ${{ runner.os }}-compile-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

    - name: compile
      run: |
        sudo apt install protobuf-compiler
        cargo build --release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: target/release/anki-widget

  release:
    runs-on: ubuntu-latest
    needs: 
      - compile
    steps:
    - uses: actions/checkout@v4
    - name: Download the binaries
      uses: actions/download-artifact@v4
    - name: Rename bins
      run: |
        mv x86_64-unknown-linux-musl/anki-widget anki-widget
    - name: Run gh release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        CHANGES=`cut -z -d "#" -f 4 CHANGELOG.md | tail -n +3`
        VERSION=`grep '^version =' Cargo.toml | head -n 1 | awk '{print $3}' | tr -d '"' | tr -d "\n"`
        TAG=`echo v$VERSION`
        LAST_RELEASE=`gh release list | grep "Latest" | grep -o "v[0-9]\+.[0-9]\+.[0-9]\+" | cut -d "v" -f 2`
        echo "Changes: $CHANGES"
        echo "Version: $VERSION"
        echo "Tag: $TAG"
        echo "Last release: $LAST_RELEASE"
        if [ "$VERSION" != "$LAST_RELEASE" ]; then
          gh release create $TAG --notes "$CHANGES" --title "v$VERSION" 
          gh release upload $TAG anki-widget
        fi
